# Generated by Django 5.2.17 on 2026-08-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('web_name', models.CharField(max_length=50)),
                ('name_avatar', models.CharField(max_length=50)),
                ('about_md', models.TextField(blank=True)),
                ('footer_text1', models.CharField(blank=True, max_length=100)),
                ('footer_text2', models.CharField(blank=True, max_length=100)),
                ('create_time', models.DateTimeField()),
            ],
        ),
    ]
