# Generated by Django 5.2.17 on 2026-08-29 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_tag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
