# Generated by Django 5.2.17 on 2026-08-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='imgs',
            field=models.TextField(blank=True, null=True, verbose_name='配图'),
        ),
    ]
