# Generated by Django 5.2.17 on 2026-08-29 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPBlacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, unpack_ipv4=True, verbose_name='IP地址')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='封禁原因')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ip_blacklists', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': 'IP黑名单',
                'verbose_name_plural': 'IP黑名单',
                'db_table': 'ip_blacklist',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, unpack_ipv4=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('device_type', models.CharField(blank=True, max_length=20, verbose_name='设备类型')),
                ('visited_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='访问时间')),
            ],
            options={
                'verbose_name': '访客记录',
                'verbose_name_plural': '访客记录',
                'db_table': 'visitor_logs',
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['ip_address', '-visited_at'], name='idx_visitor_ip_time')],
            },
        ),
    ]
