# Generated by Django 5.2.17 on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visitor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ipblacklist",
            name="ip_address",
            field=models.CharField(
                max_length=45,
                unique=True,
                verbose_name="IP地址",
            ),
        ),
    ]
