# Generated by Django 5.2.17 on 2026-08-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='articles/covers/%Y/%m/', verbose_name='封面')),
                ('content', models.TextField(verbose_name='正文')),
                ('is_draft', models.BooleanField(default=True, verbose_name='是否草稿')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'articles',
            },
        ),
    ]
